### ISSUE TITLE
Add HTML widget

### ISSUE THREAD

**Issue by imanolGOMI** [eManPrague/redmine_dashboard#1]
To add iframe for example ;)

Thanks!

**Comment by Strnadj** [comment]
Please look closer to _ClockWidget_ example with static template... You can write your own static template with iframe.

**Comment by imanolGOMI** [comment]
@Strnadj  but not is more easiest have a control that you can add and put html code and then shows the result? 

I am thinking click on add widget --> add html widget --> Put title and put HTML code in the body that will be interpretated.

I think that is amazing feature that would be one improvement this project

**Comment by imanolGOMI** [comment]
Reopens if you consider that the functionality is interesting

**Comment by Strnadj** [comment]
It seems to be a good idea, but now we are working only with previously defined widget sizes. User cannot change widget size by himself. I suppose for this functionality it will be necessary...
