### ISSUE TITLE
Support wih firefox

### ISSUE THREAD

**Issue by imanolGOMI** [eManPrague/redmine_dashboard#2]
I cant move, remove or edit the widgets with ubuntu and firefox

**Comment by Strnadj** [comment]
With latest firefox on OS X it works.. Seems to be an issue of https://github.com/troolee/gridstack.js ...

**Comment by imanolGOMI** [comment]
Ok. I have the latest firefox but sometimes fails. 3rd party issue close this issue, not problem ;)
